# Точки маршрута
## Получить точки маршрута
GET http://localhost:3000/points HTTP/1.1
Authorization: Basic VladV1984

###
## Добовление точки маршрута
POST http://localhost:3000/points HTTP/1.1
Authorization: Basic VladV1984
Content-Type: application/json

{
   "basePrice": 100,
   "dataFrom": "2025-07-21T11:30:59.000Z",
   "dataTo": "2025-07-21T12:00:59.000Z",
   "destination": null,
   "offers": [],
   "type": "bus"
}

###
## Редактирование точки маршрута
PUT http://localhost:3000/points HTTP/1.1
Authorization: Basic VladV1984
Content-Type: application/json

{
   "basePrice": 200,
   "dataFrom": "2025-07-21T11:30:59.000Z",
   "dataTo": "2025-07-21T12:00:59.000Z",
   "destination": 1,
   "offers": [1,2],
   "type": "taxi"
}

###
## Удаление точки маршрута
DELETE  http://localhost:3000/points/2 HTTP/1.1
Authorization: Bearer VladV1984
